### ISSUE TITLE
whether your rule engine algorithm does not use the RETE algorithm？

### ISSUE THREAD

**Issue by zh-12345** [zuozhenidoit/A-Rule-Engine-based-on-Python#1]
whether your rule engine algorithm does not use the RETE algorithm？Could you please consult some methods of rule matching, or recommend some materials？I am looking forward your reply.
Thank you!

**Comment by zuozhenLib** [comment]
I guess I have not use any fancy matching algorithm...
Becasue if you want to use my rule engine , you have to write rule set file in my customize format. My engine extract the facts and results then  store them in memory as a table. During matching , first look up the name of fact in table, if find a fact with the same name successfully , then ,check if the input fact value and the fact value in table have the same value. Then decide if the rule will be fired or not. 
Actually , I build the engine with no reference. I  thought it would work in this way and it did work. ;）

**Comment by zh-12345** [comment]
Thanks four reply.This is the fastest reply I have got.So your rules engine is implemented by walking through the rules one by one.Thanks!!!

**Comment by zuozhenLib** [comment]
You still there ? Do you have any algorithm recommended to matching the rules fast? Happy  to learn about~

**Comment by zh-12345** [comment]
hahahahaha ,I am still.I just recently learned about the REte algorithm, which is pretty good. This is a brief introduction of it on the website：https://en.wikipedia.org/wiki/Rete_algorithm  or https://zhuanlan.zhihu.com/p/35337081
